# Generated by Django 5.0.6 on 2024-06-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0032_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('shipped', 'shipped'), ('order-placed', 'order-placed'), ('dispatched', 'dispatched'), ('cancelled', 'cancelled'), ('delivered', 'delivered')], default='order-placed', max_length=100),
        ),
    ]
